version: 0.2
phases:
  install:
    commands:
      - pip install mkdocs
  build:
    commands:
      - mkdocs build
  post_build:
    commands:
      - echo Yeet
      - mkdocs serve
artifacts:
  files:
    - site/**/*
