version: 0.2
phases:
  install:
    commands:
      - pip install mkdocs
      - pip install awscli
  build:
    commands:
      - mkdocs build
      - aws s3 cp site s3://belphegor-bucket --recursive
  post_build:
    commands:
      - echo Yeet
      
    
artifacts:
  files:
    - site/**/*